// Generated by https://quicktype.io

export interface ClientsDatum {
  total: number;
  perPage: number;
  page: number;
  lastPage: number;
  data: Client[];
}

export interface Client {
  id: number;
  created_at: string;
  updated_at: string;
  professional_id: number;
  web: string;
  company_name: string;
  address: null | string;
  icon: null | string;
  latitude: string;
  longitude: string;
  phone: string;
  legal_representative: null | string;
  nit: null | string;
  disclaimer: null | string;
}

// Generated by https://quicktype.io

export interface ClientDetail {
  id: number;
  created_at: string;
  updated_at: string;
  professional_id: number;
  web: string;
  company_name: string;
  address: string;
  icon: string;
  latitude: string;
  longitude: string;
  phone: string;
  legal_representative: null;
  nit: string;
  disclaimer: string;
  professionals: Professional[];
  whatsapp: Whatsapp | null;
  balance: Balance | null;
  transactions: Transaction[],
}

export interface Professional {
  id: number;
  createdAt: string;
  updatedAt: string;
  name: string;
  documentType: string;
  email: string;
  phone: string;
  deletedAt: null;
  validated: number;
  available: number;
  validatedAt: null;
  photo: null | string;
  document: string;
  validatedBy: null;
  cityId: number | null;
  rate: number;
  address: null | string;
  web: null | string;
  settingId: number;
  roleId: number | null;
  sign: null | string;
  professionalCard: null | string;
}

export interface Whatsapp {
  created_at: string;
  metadata:Metadata;
}

export interface Metadata{
  
    jid: string;
    name: string;
    phone: Phone;
    imgUrl: string| null;

}
export interface Phone {
  
    mcc: string;
    mnc: string;
    os_version: string;
    wa_version: string;
    device_model: string;
    os_build_number: string;
    device_manufacturer: string;

}
export interface Balance {
  
  setting_id: string;
  balance: number|null;
  next_payment: string;
  maximum_payment: string;
  monthly_collection_frequency: number;
  value_base: number|null;
  value_base_whatsapp: number|null;

}


export interface Transaction {
  id:string;
  setting_id: string;
  description: string|null;
  value: string;
  created_at: string;
  updated_at: string;

}
