// Generated by https://quicktype.io

export interface Professional {
    id:               number;
    createdAt:        string;
    updatedAt:        string;
    name:             string;
    documentType:     string;
    email:            string;
    phone:            string;
    deletedAt:        string | null;
    validated:        boolean;
    available:        number;
    validatedAt:      string;
    photo:            string;
    document:         string;
    validatedBy:      number | null;
    cityId:           number;
    rate:             number;
    address:          string;
    web:              string;
    settingId:        number;
    roleId:           number;
    sign:             string;
    professionalCard: string;
    locked: boolean;
    lockedClinic: boolean;
}
