// Generated by https://quicktype.io

export interface TransactionsDatum {
    total:    number;
    perPage:  number;
    page:     number;
    lastPage: number;
    data:     Transaction[];
}

export interface Transaction {
    id:                  number;
    created_at:          string;
    updated_at:          string;
    value:               string;
    setting_id:          number | null;
    description:         string;
    mercadopago_id:      null | string;
    status:              string | null;
    net_received_amount: number | null;
    client:              Client | null;
}

export interface Client {
    id:                   number;
    created_at:           string;
    updated_at:           string;
    professional_id:      number;
    web:                  string;
    company_name:         string;
    address:              string;
    icon:                 string;
    latitude:             string;
    longitude:            string;
    phone:                string;
    legal_representative: null;
    nit:                  string;
    disclaimer:           string;
}

